{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}

{if $paginator->pageCount > 1}
<p class="pages">
	{if $paginator->isFirst()}
    <a href="#" class="no-padd">Předchozí</a>
	{else}
    <a href="{link this, 'page' => $paginator->page - 1}" class="no-padd">Předchozí</a>
	{/if}

	{foreach $steps as $step}
	{if $step == $paginator->page}
        <a class="curr" href="#">{$step}</a>
    {else}
        <a href="{link this, 'page' => $step}">{$step}</a>
    {/if}
	{/foreach}

	{if $paginator->isLast()}
    <a class="no-padd" href="#">Další</a>
	{else}
    <a class="no-padd" href="{link this, 'page' => $paginator->page + 1}">Další</a>
	{/if}
</p>
{/if}
